### ISSUE TITLE
Invalid Status and Improper representation when switched to 0.13 from 0.12 

### ISSUE THREAD

**Issue by pwrstar** [fivetran/great_expectations#2234]
Hi,

I noticed a difference in the way `expect_column_pair_values_A_to_be_greater_than_B` expectation result is presented in version 0.13.x compared to 0.12.x .

No changes to config or any other parameters.

Top in 0.12.x and bottom in 0.13.x :

![Screen Shot 2021-01-06 at 1 18 38 PM](https://user-images.githubusercontent.com/74983406/103823469-fdaec200-5026-11eb-8949-6be2ae6db0bb.png)

I didn’t find issues with other expectations I have though.

Thanks!

**Comment by eugmandel** [comment]
Thank you for filing this, @pwrstar ! We will triage this issue this week.

**Comment by quinten-goens** [comment]
@eugmandel This is currently still an issue in great expectations 0.13.13. Has this bugfix been included in the new version (0.13.14)?

Many thanks for the amazing work on this module!

**Comment by jarandaf** [comment]
Hi, I am also facing this issue in `0.13.14`. Also for custom expectations with Spark dataframes: is there any required work other than inheriting `SparkDFDataset` and creating methods with the `MetaSparkDFDataset` decorators? The validation runs fine but it is displayed as below:

![Captura de pantalla 2021-03-24 a las 14 20 42](https://user-images.githubusercontent.com/2277398/112317341-3e27ee80-8cac-11eb-8bf1-33c0e9d329c2.png)

**Comment by FollowJack** [comment]
Still face this issue in 0.13.19 using pandas

**Comment by Patechoc** [comment]
Like @FollowJack, I confirmed it isn't working in 0.13.19 as well. We have also a version for SQL implemented locally which execute the validation fine as shown in the table ge_validation_results, but we wait to add to the core package because of this bug when rendering in Datadocs.
If you could provide some guidance where you think the code might be wrong, we would gladly try to fix it

**Comment by talagluck** [comment]
I believe this should be resolved by #3179, so closing for now, but please feel free to re-open if that is not the case.

**Comment by sdeepak09** [comment]
Hi Team,
Thank you for this amazing library, it is super helpful. 
But I am still facing this issues with 0.15.5 using Pandas for expect_column_pair_values_A_to_be_greater_than_B expectation. @talagluck Please help.

![image](https://user-images.githubusercontent.com/22212419/168855633-43143957-108a-411d-8aa9-cfb4c54dc196.png)
