### ISSUE TITLE
TypeError: cannot pickle '_thread.RLock' object when calling SimpleCheckpoint with PySpark dataframe

### ISSUE THREAD

**Issue by jvetu** [fivetran/great_expectations#3263]
**Describe the bug**
Calling SimpleCheckpoint with PySpark dataframe in batch_data of batch_request fails with 

`TypeError: cannot pickle '_thread.RLock' object`

**To Reproduce**

```
batch_request = {"datasource_name":"my_spark_datasource",
    "data_connector_name":"my_runtime_data_connector",
    "data_asset_name":"data_asset_name",
    "runtime_parameters":{
      "batch_data": df
    },
    "batch_identifiers":{
        "some_key_maybe_pipeline_stage": "ingestion step 1",
        "some_other_key_maybe_airflow_run_id": "run 18"
    }
}

checkpoint_config = {
    "class_name": "SimpleCheckpoint",
    "validations": [
        {
            "batch_request": batch_request,
            "expectation_suite_name": expectation_suite_name,
        }
    ],
}

checkpoint = SimpleCheckpoint(
    f"_tmp_checkpoint_"+expectation_suite_name, context, **checkpoint_config
)
```

where df is a PySpark dataframe.

**Environment (please complete the following information):**
 - Great Expectations Version: 0.13.28

**Comment by talagluck** [comment]
Thanks for submitting this issue, @jvetu ! Someone from our team will review and be in touch in the next week or so.

**Comment by alex-hsp** [comment]
I am unable to use checkpoints too.

```
context.run_checkpoint(
  checkpoint_name="dim_country_checkpoint", 
  validations=[{
    "expectation_suite_name": "dim_country_profile",
    "batch_request": {
      'datasource_name': "spark_datasource",
      'data_connector_name': "dataframe_connector",
      'data_asset_name': "dim_country",
      'runtime_parameters': {'batch_data': dataframe},
      'batch_identifiers': {'table_name': 'redshift.dim_country'},
    },
    "action_list": [
      {
        'name': 'update_data_docs',
        'action': {
          'class_name': 'UpdateDataDocsAction'
        }
      }
    ]
  }]
)
```

**Comment by talagluck** [comment]
Thanks for posting, @alex-hsp! Are you getting the same error message as well? 

We have a bit of a backlog, but will get to this as soon as we are able.

**Comment by alex-hsp** [comment]
Yes. This happens because internally checkpoint tries to dump (serialize) its config which includes runtime parameters with unserializable DataFrame.

**Comment by talagluck** [comment]
Yup - we've identified that as well, @alex-hsp!

Update for @jvetu as well, we are currently working through the architecture of this, and will post updates as they arise.

Also an update, this seems to be a duplication of #2905.

**Comment by talagluck** [comment]
Hi @jvetu and @alex-hsp - I believe this has been resolved by #3388, and so I'm going to close this for now. Please keep an eye out for this in the next release, and please chime in here or feel free to open a new issue if you still have any problems. Thanks again for raising this issue!

**Comment by jvetu** [comment]
Hi @talagluck, I believe #3388 didn't fix this. I think the equivalent fix needs to be implemented for both SimpleCheckpoint and context.run_checkpoint().

**Comment by talagluck** [comment]
Thanks for this, @jvetu ! We will take a look and be in touch soon.

**Comment by NathanFarmer** [comment]
Hi @jvetu @alex-hsp! This has been addressed by PR #3502 and the fix will be included in release 0.13.38.

**Comment by jvetu** [comment]
@NathanFarmer @talagluck unfortunately error still occurs in 0.13.38 when calling context.run_checkpoint with a spark data frame in your batch request.

**Comment by NathanFarmer** [comment]
Hi @jvetu and @alex-hsp. Your batch request should be passed into the checkpoint as an object of type `RuntimeBatchRequest` not `dict`. Essentially, you just need to wrap what you already have:

```
from great_expectations.core.batch import RuntimeBatchRequest
batch_request = RuntimeBatchRequest(batch_request)
```

**Comment by jvetu** [comment]
Ah, great! All appears to be working now. Thank you very much, @NathanFarmer
